server:
  port: 8068
  servlet:
    context-path: /CertaBotOrganize

spring:
  application:
    name: CertaBotOrganize
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://192.168.0.61;databaseName=CertaBotOrganize;encrypt=false;integratedSecurity=false;
    username: giovanni.andrade
    password: gigi1704

config:
  downloadPath: /home/selenium/Downloads
  dockerPathDownload: http://192.168.1.46:8068/CertaBotOrganize/downloads/
  archivedFilesDir: D:\Arquivados\
  sentFilesDir: D:\Enviados\
  rootDir: D:\
  usuario: giovanni.andrade@certacon.com.br
  senha: 1
