server:
  port: 8063
  servlet:
    context-path: /certaBotOrganize

spring:
  application:
    name: CertaBotOrganize
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://192.168.0.61;databaseName=CertaBotOrganize;encrypt=false;integratedSecurity=false;
    username: giovanni.andrade
    password: gigi1704
