server:
  port: 8068
  servlet:
    context-path: /CertaBotOrganize

spring:
  application:
    name: CertaBotOrganize
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
  jmx:
    enabled: false

  datasource:
    url: jdbc:sqlserver://192.168.0.27;databaseName=CertaBotOrganizeDev;encrypt=false;integratedSecurity=false;
    username: giovanni.andrade
    password: gigi1704

config:
  downloadPath: /home/selenium/Downloads
  dockerPathDownload: http://192.168.1.84:8068/CertaBotOrganize/downloads/
  archivedFilesDir: D:\ARQUIVADOS\
  sentFilesDir: D:\ENVIADOS\
  rootDir: D:\
  restBuilderNFe: http://192.168.1.84:8061/CertabotNFe
  restBuilderEFDPadrao: http://192.168.1.84:8092/certabot
  usuario: giovanni.andrade@certacon.com.br
  senha: 1
